In [1]:
#importing necessary packages

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import random
import itertools
import math

In [2]:
#uploading dataframe

df=pd.read_csv('pts.csv')
df


PTS_1  PTS_2  PTS_3  PTS_4  PTS_5  PTS_6  PTS_7  PTS_8  PTS_9  PTS_10  \
0      1.0    1.0    4.0    4.0    1.0    2.0    4.0    1.0      4     3.0   
1      2.0    1.0    4.0    1.0    1.0    2.0    4.0    4.0      4     1.0   
2      3.0    2.0    1.0    3.0    2.0    3.0    2.0    3.0      2     NaN   
3      3.0    2.0    3.0    4.0    2.0    4.0    2.0    4.0      3     3.0   
4      2.0    1.0    2.0    4.0    1.0    2.0    3.0    1.0      2     1.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...     ...   
420    1.0    1.0    4.0    1.0    1.0    1.0    4.0    3.0      4     1.0   
421    2.0    1.0    2.0    1.0    1.0    2.0    2.0    3.0      1     3.0   
422    2.0    2.0    4.0    1.0    2.0    2.0    4.0    3.0      1     1.0   
423    1.0    2.0    1.0    4.0    1.0    2.0    4.0    4.0      3     1.0   
424    1.0    3.0    4.0    2.0    2.0    3.0    3.0    2.0      3     2.0   

     ...  PTS_51  PTS_52  PTS_53  PTS_54  PTS_55  PTS_56  PTS_57   SPP   RPN  \
0    ...     4.0     3.0     2.0     1.0     2.0     3.0     4.0  46.0  46.0   
1    ...     1.0     3.0     2.0     3.0     2.0     3.0     1.0  55.0  60.0   
2    ...     1.0     4.0     1.0     4.0     1.0     3.0     2.0  42.0  44.0   
3    ...     1.0     2.0     3.0     2.0     4.0     2.0     4.0  44.0  44.0   
4    ...     1.0     2.0     1.0     3.0     2.0     3.0     1.0  44.0  59.0   
..   ...     ...     ...     ...     ...     ...     ...     ...   ...   ...   
420  ...     1.0     1.0     1.0     1.0     4.0     4.0     4.0  63.0  59.0   
421  ...     3.0     4.0     NaN     2.0     3.0     4.0     1.0  54.0  64.0   
422  ...     4.0     1.0     1.0     1.0     1.0     1.0     2.0  47.0  52.0   
423  ...     2.0     3.0     1.0     2.0     4.0     1.0     1.0  55.0  68.0   
424  ...     2.0     2.0     3.0     2.0     2.0     3.0     3.0  50.0  55.0   

      SPH  
0    41.0  
1    47.0  
2    46.0  
3    45.0  
4    40.0  
..    ...  
420  49.0  
421  47.0  
422  55.0  
423  35.0  
424  52.0  

[425 rows x 60 columns]

In [3]:
#checking for nans

df.isnull().sum()

PTS_1     5
PTS_2     8
PTS_3     4
PTS_4     1
PTS_5     1
PTS_6     3
PTS_7     4
PTS_8     6
PTS_9     0
PTS_10    6
PTS_11    4
PTS_12    5
PTS_13    3
PTS_14    1
PTS_15    0
PTS_16    1
PTS_17    8
PTS_18    2
PTS_19    0
PTS_20    2
PTS_21    0
PTS_22    2
PTS_23    4
PTS_24    2
PTS_25    4
PTS_26    0
PTS_27    1
PTS_28    1
PTS_29    4
PTS_30    2
PTS_31    2
PTS_32    6
PTS_33    3
PTS_34    4
PTS_35    4
PTS_36    1
PTS_37    2
PTS_38    2
PTS_39    6
PTS_40    2
PTS_41    3
PTS_42    0
PTS_43    1
PTS_44    3
PTS_45    6
PTS_46    5
PTS_47    2
PTS_48    1
PTS_49    4
PTS_50    3
PTS_51    7
PTS_52    4
PTS_53    2
PTS_54    4
PTS_55    4
PTS_56    1
PTS_57    2
SPP       0
RPN       0
SPH       0
dtype: int64

In [4]:
#checking unique values in dataframe

unique_values = df.values.ravel()
unique_values = pd.Series(unique_values).unique()
unique_values

array([ 1.,  4.,  2.,  3., nan, 46., 41., 55., 60., 47., 42., 44., 45.,
       59., 40., 56., 57., 52., 65., 49., 39., 63., 50., 64., 53., 48.,
       30., 43., 35., 36., 67., 51., 58., 38., 61., 66., 62., 37., 54.,
       73., 29., 34., 69., 70., 33., 26., 28., 68., 74., 32., 31., 21.])

In [5]:
#removing row 248 with exceptionally high value of 21 in one question 

df.drop([248], axis=0, inplace=True)

In [6]:
#filling nans with median values of columns

for col in df.columns:
    median = df[col].median()  # Compute median value of column
    df[col] = df[col].fillna(median)  # Fill NaN values with median value
    
df

PTS_1  PTS_2  PTS_3  PTS_4  PTS_5  PTS_6  PTS_7  PTS_8  PTS_9  PTS_10  \
0      1.0    1.0    4.0    4.0    1.0    2.0    4.0    1.0      4     3.0   
1      2.0    1.0    4.0    1.0    1.0    2.0    4.0    4.0      4     1.0   
2      3.0    2.0    1.0    3.0    2.0    3.0    2.0    3.0      2     2.0   
3      3.0    2.0    3.0    4.0    2.0    4.0    2.0    4.0      3     3.0   
4      2.0    1.0    2.0    4.0    1.0    2.0    3.0    1.0      2     1.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...     ...   
420    1.0    1.0    4.0    1.0    1.0    1.0    4.0    3.0      4     1.0   
421    2.0    1.0    2.0    1.0    1.0    2.0    2.0    3.0      1     3.0   
422    2.0    2.0    4.0    1.0    2.0    2.0    4.0    3.0      1     1.0   
423    1.0    2.0    1.0    4.0    1.0    2.0    4.0    4.0      3     1.0   
424    1.0    3.0    4.0    2.0    2.0    3.0    3.0    2.0      3     2.0   

     ...  PTS_51  PTS_52  PTS_53  PTS_54  PTS_55  PTS_56  PTS_57   SPP   RPN  \
0    ...     4.0     3.0     2.0     1.0     2.0     3.0     4.0  46.0  46.0   
1    ...     1.0     3.0     2.0     3.0     2.0     3.0     1.0  55.0  60.0   
2    ...     1.0     4.0     1.0     4.0     1.0     3.0     2.0  42.0  44.0   
3    ...     1.0     2.0     3.0     2.0     4.0     2.0     4.0  44.0  44.0   
4    ...     1.0     2.0     1.0     3.0     2.0     3.0     1.0  44.0  59.0   
..   ...     ...     ...     ...     ...     ...     ...     ...   ...   ...   
420  ...     1.0     1.0     1.0     1.0     4.0     4.0     4.0  63.0  59.0   
421  ...     3.0     4.0     2.0     2.0     3.0     4.0     1.0  54.0  64.0   
422  ...     4.0     1.0     1.0     1.0     1.0     1.0     2.0  47.0  52.0   
423  ...     2.0     3.0     1.0     2.0     4.0     1.0     1.0  55.0  68.0   
424  ...     2.0     2.0     3.0     2.0     2.0     3.0     3.0  50.0  55.0   

      SPH  
0    41.0  
1    47.0  
2    46.0  
3    45.0  
4    40.0  
..    ...  
420  49.0  
421  47.0  
422  55.0  
423  35.0  
424  52.0  

[424 rows x 60 columns]

In [7]:
#checking unique values to make sure nothing went wrong 

unique_values = df.values.ravel()
unique_values = pd.Series(unique_values).unique()
unique_values

array([ 1.,  4.,  2.,  3., 46., 41., 55., 60., 47., 42., 44., 45., 59.,
       40., 56., 57., 52., 65., 49., 39., 63., 50., 64., 53., 48., 30.,
       43., 35., 36., 67., 51., 58., 38., 61., 66., 62., 37., 54., 73.,
       29., 34., 69., 70., 33., 26., 28., 68., 74., 32., 31.])

In [8]:
#changing values in inverted questions

ldr = [0, 13, 15, 17, 20, 28, 39, 42, 50, 4, 12, 16, 18, 19, 23, 30, 40, 45, 46, 3, 5, 8, 22, 24, 32, 41, 44, 54]
copy = df.copy()
for i in ldr:
    copy.iloc[:, i] = 5 - copy.iloc[:, i]
df = copy
df

PTS_1  PTS_2  PTS_3  PTS_4  PTS_5  PTS_6  PTS_7  PTS_8  PTS_9  PTS_10  \
0      4.0    1.0    4.0    1.0    4.0    3.0    4.0    1.0      1     3.0   
1      3.0    1.0    4.0    4.0    4.0    3.0    4.0    4.0      1     1.0   
2      2.0    2.0    1.0    2.0    3.0    2.0    2.0    3.0      3     2.0   
3      2.0    2.0    3.0    1.0    3.0    1.0    2.0    4.0      2     3.0   
4      3.0    1.0    2.0    1.0    4.0    3.0    3.0    1.0      3     1.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...     ...   
420    4.0    1.0    4.0    4.0    4.0    4.0    4.0    3.0      1     1.0   
421    3.0    1.0    2.0    4.0    4.0    3.0    2.0    3.0      4     3.0   
422    3.0    2.0    4.0    4.0    3.0    3.0    4.0    3.0      4     1.0   
423    4.0    2.0    1.0    1.0    4.0    3.0    4.0    4.0      2     1.0   
424    4.0    3.0    4.0    3.0    3.0    2.0    3.0    2.0      2     2.0   

     ...  PTS_51  PTS_52  PTS_53  PTS_54  PTS_55  PTS_56  PTS_57   SPP   RPN  \
0    ...     1.0     3.0     2.0     1.0     3.0     3.0     4.0  46.0  46.0   
1    ...     4.0     3.0     2.0     3.0     3.0     3.0     1.0  55.0  60.0   
2    ...     4.0     4.0     1.0     4.0     4.0     3.0     2.0  42.0  44.0   
3    ...     4.0     2.0     3.0     2.0     1.0     2.0     4.0  44.0  44.0   
4    ...     4.0     2.0     1.0     3.0     3.0     3.0     1.0  44.0  59.0   
..   ...     ...     ...     ...     ...     ...     ...     ...   ...   ...   
420  ...     4.0     1.0     1.0     1.0     1.0     4.0     4.0  63.0  59.0   
421  ...     2.0     4.0     2.0     2.0     2.0     4.0     1.0  54.0  64.0   
422  ...     1.0     1.0     1.0     1.0     4.0     1.0     2.0  47.0  52.0   
423  ...     3.0     3.0     1.0     2.0     1.0     1.0     1.0  55.0  68.0   
424  ...     3.0     2.0     3.0     2.0     3.0     3.0     3.0  50.0  55.0   

      SPH  
0    41.0  
1    47.0  
2    46.0  
3    45.0  
4    40.0  
..    ...  
420  49.0  
421  47.0  
422  55.0  
423  35.0  
424  52.0  

[424 rows x 60 columns]

In [9]:
#creating lists for normal questions for the first of three subscales in the test 
list_pts_1 = ['PTS_1','PTS_3','PTS_8','PTS_10','PTS_14','PTS_16','PTS_18','PTS_21','PTS_29','PTS_32','PTS_34','PTS_38','PTS_40','PTS_43','PTS_44','PTS_49','PTS_50','PTS_51','PTS_54']  


In [10]:
#converting the list to dataframe
pts_1=df[list_pts_1]


In [11]:
#checking unique values again
unique_values = pts_1.values.ravel()
unique_values = pd.Series(unique_values).unique()
unique_values

array([4., 1., 3., 2.])

In [12]:
#creating a column with sums of rows and sorting rows accordingly in ascending order 

pts_1_copy = pts_1.copy()
pts_1_copy.loc[:, 'sum_rows'] = pts_1_copy.sum(axis='columns')
pts_1_copy = pts_1_copy.sort_values(by=['sum_rows']).reset_index(drop=True)
pts_1 = pts_1_copy

In [13]:
#checking unique values again
unique_values = pts_1.values.ravel()
unique_values = pd.Series(unique_values).unique()

In [14]:
#creating a row with sums of columns and sorting columns accordingly in ascending order 
pts_copy = pts_1.copy()
pts_copy.loc['sum_cols', :] = pts_copy.sum(axis=0)
pts_copy = pts_copy.sort_values(by=['sum_cols'], axis=1)
pts_1 = pts_1_copy

In [15]:
#replacing 2,3,4 values with zeros; checking values 

pts_1_1=pts_1.replace({2:0,3:0,4:0})
unique_values = pts_1_1.values.ravel()
unique_values = pd.Series(unique_values).unique()
unique_values

array([ 1.,  0., 28., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 66.,
       67., 69., 71., 74.])

In [16]:
#replacing 1,3,4 values with zeros, and 2 with 1; checking values 

pts_1_2=pts_1.replace({1:0,2:1,3:0,4:0})
unique_values = pts_1_2.values.ravel()
unique_values = pd.Series(unique_values).unique()
unique_values

array([ 0.,  1., 28., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 66.,
       67., 69., 71., 74.])

In [17]:
#replacing values 1,2,4 with zeros, and 3 with one; checking values 

pts_1_3=pts_1.replace({1:0,2:0,3:1,4:0})
unique_values = pts_1_3.values.ravel()
unique_values = pd.Series(unique_values).unique()
unique_values

array([ 0.,  1., 28., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 66.,
       67., 69., 71., 74.])

In [18]:
#replacing values 1,2,3 with zeros, and 4 with one; checking values 

pts_1_4=pts_1.replace({1:0,2:0,3:0,4:1})
unique_values = pts_1_4.values.ravel()
unique_values = pd.Series(unique_values).unique()
unique_values

array([ 0., 28.,  1., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 66.,
       67., 69., 71., 74.])

In [19]:
#grouping rows with identical 'sum_rows' by mean values, result being probability to answer question in certain way for specified score 

pts_1_1=pts_1_1.groupby('sum_rows', as_index=False).mean()
column_to_move = pts_1_1.pop('sum_rows')
pts_1_1.insert(len(pts_1_1.columns), 'sum_rows', column_to_move)

pts_1_2=pts_1_2.groupby('sum_rows', as_index=False).mean()
column_to_move = pts_1_2.pop('sum_rows')
pts_1_2.insert(len(pts_1_2.columns), 'sum_rows', column_to_move)

pts_1_3=pts_1_3.groupby('sum_rows', as_index=False).mean()
column_to_move = pts_1_3.pop('sum_rows')
pts_1_3.insert(len(pts_1_3.columns), 'sum_rows', column_to_move)

pts_1_4=pts_1_4.groupby('sum_rows', as_index=False).mean()
column_to_move = pts_1_4.pop('sum_rows')
pts_1_4.insert(len(pts_1_4.columns), 'sum_rows', column_to_move)

In [20]:
#rounding probability values to second decimal 

pts_1_1=round(pts_1_1,2)
pts_1_2=round(pts_1_2,2)
pts_1_3=round(pts_1_3,2)
pts_1_4=round(pts_1_4,2)


In [21]:
#pts_1_1.iloc[:,:-1].columns

In [22]:
#creating function that renders three matrices: 
#with frequency of occurence of random indices drawn from a flattened matrix, 
#with ones and zeros representing comparison between randomly drawn values , 
#with ones representing successful comparison for the value on the left 

def calculate_scores(pts):
    rows_to_lists = pts.iloc[:, :-1].values.tolist()
    flat_list = [item for sublist in rows_to_lists for item in sublist]
    acm_list = []
    freq_list = [0 for _ in flat_list]
    item_score = [0 for _ in flat_list]

    for x in range(len(flat_list)):
        indices = []
        acm_prep = []
        acm_prep.append((flat_list[x], x))

        random_num = np.random.choice(
            range(x + 1, len(flat_list)), 
            size=math.ceil((len(flat_list) - x - 1) / 2),
            replace=False)

        indices.extend(random_num)
        sorted_indices = sorted(indices)

        for index in sorted_indices:
            freq_list[index] += 1
            freq_list[x]+=1
            acm_prep.append((flat_list[index], index))
        for y in range(len(acm_prep) - 1):
            if acm_prep[0][0] < acm_prep[y + 1][0]:
                acm_list.append(1)
                item_score[acm_prep[0][1]] += 1
            else:
                acm_list.append(0)
    return freq_list, acm_list, item_score

In [23]:
#calling function calculate_scores

freq_list_1_1, acm_list_1_1, item_score_1_1 = calculate_scores(pts_1_1)
freq_list_1_2, acm_list_1_2, item_score_1_2 = calculate_scores(pts_1_2)
freq_list_1_3, acm_list_1_3, item_score_1_3 = calculate_scores(pts_1_3)
freq_list_1_4, acm_list_1_4, item_score_1_4 = calculate_scores(pts_1_4)

In [24]:
#ACM for pts_1_1

sum(acm_list_1_1)/len(acm_list_1_1)

0.2062949047524883

In [25]:
#ACM for pts_1_2

sum(acm_list_1_2)/len(acm_list_1_2)

0.2800738250609716

In [26]:
#ACM for pts_1_3

sum(acm_list_1_3)/len(acm_list_1_3)

0.4882209478610507

In [27]:
#ACM for pts_1_4

sum(acm_list_1_4)/len(acm_list_1_4)

0.7391800145013513

In [28]:
#transforming item_score lists to ndarray

item_score_ndarray_1_1=np.reshape(item_score_1_1, (41, 19))
item_score_ndarray_1_2=np.reshape(item_score_1_2, (41, 19))
item_score_ndarray_1_3=np.reshape(item_score_1_3, (41, 19))
item_score_ndarray_1_4=np.reshape(item_score_1_4, (41, 19))


freq_list_ndarray_1_1=np.reshape(freq_list_1_1, (41,19))
freq_list_ndarray_1_2=np.reshape(freq_list_1_2, (41,19))
freq_list_ndarray_1_3=np.reshape(freq_list_1_3, (41,19))
freq_list_ndarray_1_4=np.reshape(freq_list_1_4, (41,19))

In [29]:
#transforming item_score_ndarray to matrices

df_item_score_1_1=pd.DataFrame(item_score_ndarray_1_1, columns=pts_1_1.iloc[:,:-1].columns)
df_freq_list_1_1=pd.DataFrame(freq_list_ndarray_1_1, columns=pts_1_1.iloc[:,:-1].columns)

df_item_score_1_2=pd.DataFrame(item_score_ndarray_1_2, columns=pts_1_2.iloc[:,:-1].columns)
df_freq_list_1_2=pd.DataFrame(freq_list_ndarray_1_2, columns=pts_1_2.iloc[:,:-1].columns)

df_item_score_1_3=pd.DataFrame(item_score_ndarray_1_3, columns=pts_1_3.iloc[:,:-1].columns)
df_freq_list_1_3=pd.DataFrame(freq_list_ndarray_1_3, columns=pts_1_3.iloc[:,:-1].columns)

df_item_score_1_4=pd.DataFrame(item_score_ndarray_1_4, columns=pts_1_4.iloc[:,:-1].columns)
df_freq_list_1_4=pd.DataFrame(freq_list_ndarray_1_4, columns=pts_1_4.iloc[:,:-1].columns)

In [30]:
#calculating quality of questions through ACM

item_quality_1_1 = df_item_score_1_1.div(df_freq_list_1_1)
item_quality_1_2 = df_item_score_1_2.div(df_freq_list_1_2)
item_quality_1_3 = df_item_score_1_3.div(df_freq_list_1_3)
item_quality_1_4 = df_item_score_1_4.div(df_freq_list_1_4)

In [31]:
#rounding values of questions quality to second decimals, 
#they'll subsequently be added to each other and divided by four to yield mean and compared with IRT results,
#yet another question quality test, but this time with grounded foundations in statistics 

means_1_1 = round(item_quality_1_1.mean(), 2)
means_1_2 = round(item_quality_1_2.mean(), 2)
means_1_3 = round(item_quality_1_3.mean(), 2)
means_1_4 = round(item_quality_1_4.mean(), 2)


In [32]:
means_1_1

PTS_1     0.17
PTS_3     0.09
PTS_8     0.07
PTS_10    0.07
PTS_14    0.14
PTS_16    0.11
PTS_18    0.13
PTS_21    0.13
PTS_29    0.15
PTS_32    0.08
PTS_34    0.09
PTS_38    0.09
PTS_40    0.15
PTS_43    0.13
PTS_44    0.07
PTS_49    0.09
PTS_50    0.06
PTS_51    0.10
PTS_54    0.05
dtype: float64